In [1]:
import numpy as np
import pandas as pd

# Creating a NN structure

        The below class is to create a single neuron with weights

In [2]:
class Layer:
        
    def initializeLayer(self,layerSize,prevLayerSize):
        self.weights =np.array([np.random.rand(prevLayerSize)])
        self.layerSize = layerSize
        count =0
        for i in range(layerSize-1):
            weight = np.array([np.random.rand(prevLayerSize)])
            self.weights= np.vstack([self.weights,weight])
            self.weights = np.array(self.weights)
            
    def getWeights(self):
        return self.weights
    def getLayerSize(self):
        return self.weights

In [13]:
inputLayerSize = 3 
hiddenLayer = Layer()
hiddenLayer.initializeLayer(5,inputLayerSize)
print("#initial Weights of hidden Layer")
print("\n")
print(hiddenLayer.getWeights())

print("\n\n")

outputLayer = Layer()
outputLayer.initializeLayer(1,5)
print("#initial Weights of output Layer")
print("\n")
print(outputLayer.getWeights())

#initial Weights of hidden Layer


[[0.83792678 0.77447853 0.96256927]
 [0.19041368 0.36418753 0.67300466]
 [0.88119971 0.97738752 0.26592086]
 [0.04794752 0.1749117  0.1414844 ]
 [0.69492009 0.1507217  0.54292168]]



#initial Weights of output Layer


[[0.29975519 0.51558966 0.14746423 0.40151323 0.03103303]]


In [30]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

def feedForward(inputLayer,hiddenLayer,outputLayer):
    output =0
    hiddenLayerWeights = np.copy(hiddenLayer.getWeights())
    outputLayerWeights = np.copy(outputLayer.getWeights())
    
    hiddenLayerOutput = []
    for i in range(len(hiddenLayer.getWeights())):
        neuron = np.copy(hiddenLayerWeights[i])
        for j in range(len(inputLayer)):
            hiddenLayerOutput.append(sigmoid(np.sum(inputLayer[j]*neuron)))
    hiddenLayerOutput_np = np.array(hiddenLayerOutput)
    for i in range(len(outputLayer.getWeights())):
        neuron = np.copy(outputLayerWeights[i])
        for j in range(len(hiddenLayerOutput_np)):
            output = sigmoid(np.sum(hiddenLayerOutput_np[j]*neuron))
            
    return output

In [31]:
inputLayer = np.array([1,1,0])
feedForward(inputLayer,hiddenLayer,outputLayer)

0.6676726811670646

In [ ]:
def meanSquareError(output, expectedOut):
    return ((output-expectedOut)**2)/2