In [10]:
import numpy as np
import pandas as pd

# Creating a NN structure

        The below class is to create a single neuron with weights

In [54]:
class Layer:
        
    def initializeLayer(self,layerSize,prevLayerSize):
        self.weights =np.array([np.random.rand(prevLayerSize)])
        count =0
        for i in range(layerSize-1):
            weight = np.array([np.random.rand(prevLayerSize)])
            self.weights= np.vstack([self.weights,weight])
            self.weights = np.array(self.weights)
            
    def printWeights(self):
        print(self.weights)

In [61]:
inputLayerSize = 3 
hiddenLayer = Layer()
hiddenLayer.initializeLayer(5,inputLayerSize)
print("#initial Weights of hidden Layer")
print("\n")
hiddenLayer.printWeights()

print("\n\n")

outputLayer = Layer()
outputLayer.initializeLayer(1,5)
print("#initial Weights of output Layer")
print("\n")
outputLayer.printWeights()

#initial Weights of hidden Layer


[[0.09633987 0.61117789 0.0803517 ]
 [0.49341438 0.57113084 0.91153339]
 [0.3489184  0.74298195 0.10186791]
 [0.31059617 0.8042466  0.16659647]
 [0.543935   0.62274539 0.60869922]]



#initial Weights of output Layer


[[0.7991179  0.23118943 0.36658371 0.79481272 0.70165994]]


In [ ]:
def feedForward(inputLayer,hiddenLayer,outputLayer):
    output =0
    for i in range(len(inputLayer)):
        
    return output